### ISSUE TITLE
Класс container должен лежать внутри header (например), а сам header тянется на 100% от экрана

### ISSUE THREAD

**Issue by igosheva** [MaksimOrekhov/Coworking#1]
https://github.com/MaksimOrekhov/Coworking/blob/96faad02aaf650db0cf9eaa4649472345a71a9a3/index.html#L19

**Comment by igosheva** [comment]
Пример https://jsfiddle.net/7g841txm/

**Comment by MaksimOrekhov** [comment]
Done. Вот это была очень глупая ошибка, зато теперь разобрался как это работает =)
