### ISSUE TITLE
Составное свойство backgound пишем отдельно

### ISSUE THREAD

**Issue by igosheva** [MaksimOrekhov/Coworking#9]
https://github.com/MaksimOrekhov/Coworking/blob/96faad02aaf650db0cf9eaa4649472345a71a9a3/css/main.css#L24

**Comment by igosheva** [comment]
В данном случае вообще нельзя задавать логотип бэкграундом (уже писала в другой правке)

**Comment by MaksimOrekhov** [comment]
Done
